name: dependabot
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    if: |
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.title, 'build(deps): bump react-native from ')
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2

      - name: Get react-native version
        run: |
          PULL_REQUEST_TITLE="${{ github.event.pull_request.head.ref }}"
          REACT_NATIVE_VERSION="${PULL_REQUEST_TITLE#* to }"
          echo "REACT_NATIVE_VERSION=$REACT_NATIVE_VERSION" >> $GITHUB_ENV

      - name: Undo last commit
        run: git reset --hard HEAD~

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Configure Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Upgrade react-native
        run: |
          yarn react-native upgrade ${{ env.REACT_NATIVE_VERSION }}
          cd ios && rm Podfile.lock && pod install && cd -

      - name: Git commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ github.event.pull_request.title }}
          add_options: '-A'
          push_options: '--force'
