name: e2e-android
on: push

jobs:
  e2e-android:
    runs-on: macos-latest
    env:
      DETOX_CONFIGURATION: android.emu.release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install Yarn dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: temurin
          java-version: 17

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: android/app/build
          key: ${{ runner.os }}-detox-build
          restore-keys: |
            ${{ runner.os }}-detox-build

      - name: Patch build
        run: |
          # https://wix.github.io/Detox/docs/troubleshooting/running-tests/#if-you-do-see-your-app-running-on-the-device
          sed -i '' 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          # https://github.com/facebook/react-native/issues/36207#issuecomment-1435838521
          sed -i '' 's/android {/android { testBuildType "release"/' android/app/build.gradle

      - name: Detox build
        run: yarn detox build --configuration ${{ env.DETOX_CONFIGURATION }}

      - name: Get device name
        id: device
        run: node -e "console.log('AVD_NAME=' + require('./.detoxrc').devices.emulator.device.avdName)" >> $GITHUB_OUTPUT

      - name: Detox test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          avd-name: ${{ steps.device.outputs.AVD_NAME }}
          profile: pixel
          script: yarn detox test --configuration ${{ env.DETOX_CONFIGURATION }} --cleanup --headless --record-logs all

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: artifacts
